version: 2
snapshot:
  staticSnapshots:
    baseUrl: http://localhost:6006
    snapshots:
      - name: Storybook iframe
        url: /iframe.html
      - name: Storybook index
        url: /index.html